apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  namespace: kikist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: converter-service:latest
          # ports:
          #   - containerPort: 8000
          envFrom:
            - configMapRef:
                name: queue-config
            - configMapRef:
                name: converter-config

          volumeMounts:
            - mountPath: /data/blob-storage
              name: blob-storage

      volumes:
        - name: blob-storage
          persistentVolumeClaim:
            claimName: blob-storage-disk-claim
