set positional-arguments
set fallback := true

set shell := ["bash", "-cue"]
root_dir := justfile_directory()

api-store-key:
    cd "{{root_dir}}" && \
        uuid=$(uuidgen) && \
        http PUT http://localhost:8080/api/v1/demo/keys/$uuid \
            public_key=$uuid \
            private_key_encrypted=$uuid && \
        http GET http://localhost:8080/api/v1/demo/keys/$uuid

run: api-store-key
