set positional-arguments
set fallback := true

set shell := ["bash", "-cue"]
root_dir := justfile_directory()

api-store-get-key:
    echo "Storing and getting a public/private key."
    cd "{{root_dir}}" && \
        key_id=$(http PUT http://localhost:8080/api/v1/demo-user/keys \
            public_key="asdf" \
            private_key_encrypted="asdf" | jq -re .key_id) && \
        http -p HBhb GET http://localhost:8080/api/v1/demo-user/keys/$key_id

run: api-store-get-key
