apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: kikist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: db-migration
          image: api-db-migration:latest
          envFrom:
            - configMapRef:
                name: db-config

      containers:
        - name: service
          image: api-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: db-config
            - configMapRef:
                name: api-config
      securityContext:
        fsGroup: 1000
