kind: Service
apiVersion: v1
metadata:
  namespace: kikist
  name: api
  labels:
    app: api
    type: LoadBalancer
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: api
