set positional-arguments
set fallback := true
set shell := ["bash", "-cue"]

comp_dir := justfile_directory()
root_dir := `git rev-parse --show-toplevel`

build *args:
    cd "{{comp_dir}}" && cargo build "${@:1}"

build-image *args:
    # docker build --progress plain "${@:1}" -t "kikist-api-service:test" -f docker/service/Dockerfile "{{root_dir}}"
    cd "{{comp_dir}}" && docker build --progress plain "${@:1}" -t "kikist-api-db-migration:test" -f docker/db-migration/Dockerfile "{{root_dir}}"

watch:
    cd "{{comp_dir}}" && cargo watch -x 'build'

db-migration:
    cd "{{comp_dir}}" && \
        source .env && \
        diesel migration run --config-file diesel.toml

db-migration-redo:
    cd "{{comp_dir}}" && \
        source .env && \
        diesel migration redo --all --config-file diesel.toml

format:
    cd "{{comp_dir}}" && \
    	docker run -v "{{root_dir}}:/repo" -v "$(pwd):/workspace" -w "/workspace" \
    	instrumentisto/rust:nightly-alpine cargo fmt -- --config-path /repo
