cm = load_dynamic(os.path.join(config.main_dir, ".tilt/Tiltfile"))
get_component_config = cm["get_component_config"]
load_settings = cm["load_settings"]

settings = load_settings()
config = get_component_config(__file__)
print("Configuring component:", config["name"])

for image_type, img_settings in config["images"].items():
    if img_settings == None:
        continue

    docker_build(
        ref=img_settings["ref"],
        context=cm["root_dir"],
        dockerfile=img_settings["dockerfile"],
        build_args={
            "BUILD_TYPE": settings["build-type"],
            "ENABLE_BACKTRACE": "1" if settings["enable-backtrace"] else "0",
        }.update(img_settings["build-args"]),
    )

k8s_yaml(kustomize(config["manifest-dir"]))
k8s_resource(workload=config["name"], port_forwards="8080:8000")
