apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
  namespace: kikist
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: mongodb-data
  resources:
    requests:
      storage: 500M
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data
  namespace: kikist
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500M
  hostPath:
    path: /data/mongo
