# Ignore everything, and only include stuff we need.
**

!tools/docker/**

!Cargo.toml
!Cargo.lock

!components/client/**/Cargo.toml
!components/client/**/Cargo.lock
!components/client/**/*.rs

!components/common/**/Cargo.toml
!components/common/**/Cargo.lock
!components/common/**/*.rs
