# Ignore everything, and only include stuff we need.
**

!tools/docker/**

!Cargo.toml
!Cargo.lock

!components/converter/**/Cargo.toml
!components/converter/**/Cargo.lock
!components/converter/**/*.rs

!components/common/**/Cargo.toml
!components/common/**/Cargo.lock
!components/common/**/*.rs
